# Dockerfile.collector
FROM python:3.10-slim

WORKDIR /app

COPY collector/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY collector/ ./collector/

WORKDIR /app/collector

ENV PYTHONUNBUFFERED=1

CMD ["python", "kis_ws_client.py"]
