# 베이스 이미지 선택 (Python 3.10 슬림 버전)
FROM python:3.10-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 패키지 설치 (루트의 requirements.txt 사용)
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# 코드 복사
COPY ./AI /app/AI

# 환경 변수 설정
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=backend.settings
ENV PYTHONPATH=/app

# 기본 명령어 (model_learn.py 실행)
CMD ["python", "AI/model_learn.py"]
