# Generated by Django 5.2 on 2025-05-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'date'], name='core_dailyp_symbol_224f83_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
