# Generated by Django 5.2 on 2025-05-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='normalized_DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'date'], name='core_normal_symbol_7d9e6e_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
